//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.08 at 02:41:52 AM EAT 
//


package philae.ach;

import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlElementDecl;
import jakarta.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the philae.ach package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _PostInwardTransferResponse_QNAME = new QName("http://ach.PHilae/", "postInwardTransferResponse");
    private final static QName _ProcessOutwardEftTransferResponse_QNAME = new QName("http://ach.PHilae/", "processOutwardEftTransferResponse");
    private final static QName _QueryOutwardTransfersResponse_QNAME = new QName("http://ach.PHilae/", "queryOutwardTransfersResponse");
    private final static QName _ConfirmOutwardTransfer_QNAME = new QName("http://ach.PHilae/", "confirmOutwardTransfer");
    private final static QName _QueryOutwardTransfers_QNAME = new QName("http://ach.PHilae/", "queryOutwardTransfers");
    private final static QName _QueryDepositAccount_QNAME = new QName("http://ach.PHilae/", "queryDepositAccount");
    private final static QName _LoginUserResponse_QNAME = new QName("http://ach.PHilae/", "loginUserResponse");
    private final static QName _QueryDepositAccountResponse_QNAME = new QName("http://ach.PHilae/", "queryDepositAccountResponse");
    private final static QName _ProcessOutwardEftTransfer_QNAME = new QName("http://ach.PHilae/", "processOutwardEftTransfer");
    private final static QName _PostInwardTransfer_QNAME = new QName("http://ach.PHilae/", "postInwardTransfer");
    private final static QName _ProcessOutwardRtgsTransferResponse_QNAME = new QName("http://ach.PHilae/", "processOutwardRtgsTransferResponse");
    private final static QName _ProcessOutwardRtgsTransfer_QNAME = new QName("http://ach.PHilae/", "processOutwardRtgsTransfer");
    private final static QName _LoginUser_QNAME = new QName("http://ach.PHilae/", "loginUser");
    private final static QName _ConfirmOutwardTransferResponse_QNAME = new QName("http://ach.PHilae/", "confirmOutwardTransferResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: philae.ach
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TlDrawer }
     * 
     */
    public TlDrawer createTlDrawer() {
        return new TlDrawer();
    }

    /**
     * Create an instance of {@link TrList }
     * 
     */
    public TrList createTrList() {
        return new TrList();
    }

    /**
     * Create an instance of {@link UsRole }
     * 
     */
    public UsRole createUsRole() {
        return new UsRole();
    }

    /**
     * Create an instance of {@link BnUser }
     * 
     */
    public BnUser createBnUser() {
        return new BnUser();
    }

    /**
     * Create an instance of {@link ProcessOutwardEftTransfer }
     * 
     */
    public ProcessOutwardEftTransfer createProcessOutwardEftTransfer() {
        return new ProcessOutwardEftTransfer();
    }

    /**
     * Create an instance of {@link QueryDepositAccountResponse }
     * 
     */
    public QueryDepositAccountResponse createQueryDepositAccountResponse() {
        return new QueryDepositAccountResponse();
    }

    /**
     * Create an instance of {@link LoginUserResponse }
     * 
     */
    public LoginUserResponse createLoginUserResponse() {
        return new LoginUserResponse();
    }

    /**
     * Create an instance of {@link QueryDepositAccount }
     * 
     */
    public QueryDepositAccount createQueryDepositAccount() {
        return new QueryDepositAccount();
    }

    /**
     * Create an instance of {@link ConfirmOutwardTransfer }
     * 
     */
    public ConfirmOutwardTransfer createConfirmOutwardTransfer() {
        return new ConfirmOutwardTransfer();
    }

    /**
     * Create an instance of {@link QueryOutwardTransfers }
     * 
     */
    public QueryOutwardTransfers createQueryOutwardTransfers() {
        return new QueryOutwardTransfers();
    }

    /**
     * Create an instance of {@link QueryOutwardTransfersResponse }
     * 
     */
    public QueryOutwardTransfersResponse createQueryOutwardTransfersResponse() {
        return new QueryOutwardTransfersResponse();
    }

    /**
     * Create an instance of {@link ProcessOutwardEftTransferResponse }
     * 
     */
    public ProcessOutwardEftTransferResponse createProcessOutwardEftTransferResponse() {
        return new ProcessOutwardEftTransferResponse();
    }

    /**
     * Create an instance of {@link PostInwardTransferResponse }
     * 
     */
    public PostInwardTransferResponse createPostInwardTransferResponse() {
        return new PostInwardTransferResponse();
    }

    /**
     * Create an instance of {@link ConfirmOutwardTransferResponse }
     * 
     */
    public ConfirmOutwardTransferResponse createConfirmOutwardTransferResponse() {
        return new ConfirmOutwardTransferResponse();
    }

    /**
     * Create an instance of {@link LoginUser }
     * 
     */
    public LoginUser createLoginUser() {
        return new LoginUser();
    }

    /**
     * Create an instance of {@link ProcessOutwardRtgsTransfer }
     * 
     */
    public ProcessOutwardRtgsTransfer createProcessOutwardRtgsTransfer() {
        return new ProcessOutwardRtgsTransfer();
    }

    /**
     * Create an instance of {@link ProcessOutwardRtgsTransferResponse }
     * 
     */
    public ProcessOutwardRtgsTransferResponse createProcessOutwardRtgsTransferResponse() {
        return new ProcessOutwardRtgsTransferResponse();
    }

    /**
     * Create an instance of {@link PostInwardTransfer }
     * 
     */
    public PostInwardTransfer createPostInwardTransfer() {
        return new PostInwardTransfer();
    }

    /**
     * Create an instance of {@link TaResponse }
     * 
     */
    public TaResponse createTaResponse() {
        return new TaResponse();
    }

    /**
     * Create an instance of {@link TaTransfer }
     * 
     */
    public TaTransfer createTaTransfer() {
        return new TaTransfer();
    }

    /**
     * Create an instance of {@link AcQuery }
     * 
     */
    public AcQuery createAcQuery() {
        return new AcQuery();
    }

    /**
     * Create an instance of {@link TaQuery }
     * 
     */
    public TaQuery createTaQuery() {
        return new TaQuery();
    }

    /**
     * Create an instance of {@link TaAccount }
     * 
     */
    public TaAccount createTaAccount() {
        return new TaAccount();
    }

    /**
     * Create an instance of {@link CnCurrency }
     * 
     */
    public CnCurrency createCnCurrency() {
        return new CnCurrency();
    }

    /**
     * Create an instance of {@link UlRequest }
     * 
     */
    public UlRequest createUlRequest() {
        return new UlRequest();
    }

    /**
     * Create an instance of {@link UlResponse }
     * 
     */
    public UlResponse createUlResponse() {
        return new UlResponse();
    }

    /**
     * Create an instance of {@link TaRequest }
     * 
     */
    public TaRequest createTaRequest() {
        return new TaRequest();
    }

    /**
     * Create an instance of {@link UrLimit }
     * 
     */
    public UrLimit createUrLimit() {
        return new UrLimit();
    }

    /**
     * Create an instance of {@link TlDrawer.Currencies }
     * 
     */
    public TlDrawer.Currencies createTlDrawerCurrencies() {
        return new TlDrawer.Currencies();
    }

    /**
     * Create an instance of {@link TrList.Transfers }
     * 
     */
    public TrList.Transfers createTrListTransfers() {
        return new TrList.Transfers();
    }

    /**
     * Create an instance of {@link UsRole.Limits }
     * 
     */
    public UsRole.Limits createUsRoleLimits() {
        return new UsRole.Limits();
    }

    /**
     * Create an instance of {@link UsRole.Drawers }
     * 
     */
    public UsRole.Drawers createUsRoleDrawers() {
        return new UsRole.Drawers();
    }

    /**
     * Create an instance of {@link BnUser.Roles }
     * 
     */
    public BnUser.Roles createBnUserRoles() {
        return new BnUser.Roles();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PostInwardTransferResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ach.PHilae/", name = "postInwardTransferResponse")
    public JAXBElement<PostInwardTransferResponse> createPostInwardTransferResponse(PostInwardTransferResponse value) {
        return new JAXBElement<PostInwardTransferResponse>(_PostInwardTransferResponse_QNAME, PostInwardTransferResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ProcessOutwardEftTransferResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ach.PHilae/", name = "processOutwardEftTransferResponse")
    public JAXBElement<ProcessOutwardEftTransferResponse> createProcessOutwardEftTransferResponse(ProcessOutwardEftTransferResponse value) {
        return new JAXBElement<ProcessOutwardEftTransferResponse>(_ProcessOutwardEftTransferResponse_QNAME, ProcessOutwardEftTransferResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QueryOutwardTransfersResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ach.PHilae/", name = "queryOutwardTransfersResponse")
    public JAXBElement<QueryOutwardTransfersResponse> createQueryOutwardTransfersResponse(QueryOutwardTransfersResponse value) {
        return new JAXBElement<QueryOutwardTransfersResponse>(_QueryOutwardTransfersResponse_QNAME, QueryOutwardTransfersResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ConfirmOutwardTransfer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ach.PHilae/", name = "confirmOutwardTransfer")
    public JAXBElement<ConfirmOutwardTransfer> createConfirmOutwardTransfer(ConfirmOutwardTransfer value) {
        return new JAXBElement<ConfirmOutwardTransfer>(_ConfirmOutwardTransfer_QNAME, ConfirmOutwardTransfer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QueryOutwardTransfers }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ach.PHilae/", name = "queryOutwardTransfers")
    public JAXBElement<QueryOutwardTransfers> createQueryOutwardTransfers(QueryOutwardTransfers value) {
        return new JAXBElement<QueryOutwardTransfers>(_QueryOutwardTransfers_QNAME, QueryOutwardTransfers.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QueryDepositAccount }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ach.PHilae/", name = "queryDepositAccount")
    public JAXBElement<QueryDepositAccount> createQueryDepositAccount(QueryDepositAccount value) {
        return new JAXBElement<QueryDepositAccount>(_QueryDepositAccount_QNAME, QueryDepositAccount.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LoginUserResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ach.PHilae/", name = "loginUserResponse")
    public JAXBElement<LoginUserResponse> createLoginUserResponse(LoginUserResponse value) {
        return new JAXBElement<LoginUserResponse>(_LoginUserResponse_QNAME, LoginUserResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QueryDepositAccountResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ach.PHilae/", name = "queryDepositAccountResponse")
    public JAXBElement<QueryDepositAccountResponse> createQueryDepositAccountResponse(QueryDepositAccountResponse value) {
        return new JAXBElement<QueryDepositAccountResponse>(_QueryDepositAccountResponse_QNAME, QueryDepositAccountResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ProcessOutwardEftTransfer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ach.PHilae/", name = "processOutwardEftTransfer")
    public JAXBElement<ProcessOutwardEftTransfer> createProcessOutwardEftTransfer(ProcessOutwardEftTransfer value) {
        return new JAXBElement<ProcessOutwardEftTransfer>(_ProcessOutwardEftTransfer_QNAME, ProcessOutwardEftTransfer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PostInwardTransfer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ach.PHilae/", name = "postInwardTransfer")
    public JAXBElement<PostInwardTransfer> createPostInwardTransfer(PostInwardTransfer value) {
        return new JAXBElement<PostInwardTransfer>(_PostInwardTransfer_QNAME, PostInwardTransfer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ProcessOutwardRtgsTransferResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ach.PHilae/", name = "processOutwardRtgsTransferResponse")
    public JAXBElement<ProcessOutwardRtgsTransferResponse> createProcessOutwardRtgsTransferResponse(ProcessOutwardRtgsTransferResponse value) {
        return new JAXBElement<ProcessOutwardRtgsTransferResponse>(_ProcessOutwardRtgsTransferResponse_QNAME, ProcessOutwardRtgsTransferResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ProcessOutwardRtgsTransfer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ach.PHilae/", name = "processOutwardRtgsTransfer")
    public JAXBElement<ProcessOutwardRtgsTransfer> createProcessOutwardRtgsTransfer(ProcessOutwardRtgsTransfer value) {
        return new JAXBElement<ProcessOutwardRtgsTransfer>(_ProcessOutwardRtgsTransfer_QNAME, ProcessOutwardRtgsTransfer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LoginUser }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ach.PHilae/", name = "loginUser")
    public JAXBElement<LoginUser> createLoginUser(LoginUser value) {
        return new JAXBElement<LoginUser>(_LoginUser_QNAME, LoginUser.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ConfirmOutwardTransferResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ach.PHilae/", name = "confirmOutwardTransferResponse")
    public JAXBElement<ConfirmOutwardTransferResponse> createConfirmOutwardTransferResponse(ConfirmOutwardTransferResponse value) {
        return new JAXBElement<ConfirmOutwardTransferResponse>(_ConfirmOutwardTransferResponse_QNAME, ConfirmOutwardTransferResponse.class, null, value);
    }

}
