//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.08 at 02:41:52 AM EAT 
//
package philae.ach;

import java.io.Serializable;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for processOutwardEftTransfer complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType name="processOutwardEftTransfer">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="transfer" type="{http://ach.PHilae/}taTransfer" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "processOutwardEftTransfer", propOrder = {
    "transfer"
})
@XmlRootElement(name = "transfer")
public class ProcessOutwardEftTransfer implements Serializable {

    protected TaTransfer transfer;

    /**
     * Gets the value of the transfer property.
     *
     * @return possible object is {@link TaTransfer }
     *
     */
    public TaTransfer getTransfer() {
        return transfer;
    }

    /**
     * Sets the value of the transfer property.
     *
     * @param value allowed object is {@link TaTransfer }
     *
     */
    public void setTransfer(TaTransfer value) {
        this.transfer = value;
    }

}
