//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.08 at 02:41:52 AM EAT 
//
package philae.ach;

import lombok.ToString;

import java.io.Serializable;
import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

/**
 * <p>
 * Java class for taTransfer complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType name="taTransfer">
 *   &lt;complexContent>
 *     &lt;extension base="{http://ach.PHilae/}taRequest">
 *       &lt;sequence>
 *         &lt;element name="txnRef" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="createDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="employeeId" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="supervisorId" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="transferType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="currency" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="amount" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="exchangeRate" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="receiverBank" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="receiverAccount" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="receiverName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="senderBank" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="senderAccount" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="senderName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="scheme" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="txnId" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="contraAccount" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="reversal" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="userRole" type="{http://ach.PHilae/}usRole"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "taTransfer", propOrder = {
    "txnRef",
    "createDate",
    "valueDate",
    "employeeId",
    "supervisorId",
    "transferType",
    "currency",
    "amount",
    "exchangeRate",
    "debitFxRate",
    "creditFxRate",
    "receiverBank",
    "receiverAccount",
    "receiverName",
    "senderBank",
    "senderAccount",
    "senderName",
    "description",
    "scheme",
    "txnId",
    "contraAccount",
    "reversal",
    "userRole"
})
@ToString
public class TaTransfer
        extends TaRequest implements Serializable {

    @XmlElement(required = true)
    protected String txnRef;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar createDate;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar valueDate;
    protected Long employeeId;
    protected Long supervisorId;
    @XmlElement(required = true)
    protected String transferType;
    @XmlElement(required = true)
    protected String currency;
    @XmlElement(required = true)
    protected BigDecimal amount;
    @XmlElement(required = true, nillable = true)
    protected BigDecimal exchangeRate;
    @XmlElement(required = true, nillable = true)
    protected BigDecimal debitFxRate;
    @XmlElement(required = true, nillable = true)
    protected BigDecimal creditFxRate;
    @XmlElement(required = true)
    protected String receiverBank;
    @XmlElement(required = true)
    protected String receiverAccount;
    @XmlElement(required = true, nillable = true)
    protected String receiverName;
    @XmlElement(required = true)
    protected String senderBank;
    @XmlElement(required = true)
    protected String senderAccount;
    @XmlElement(required = true, nillable = true)
    protected String senderName;
    @XmlElement(required = true)
    protected String description;
    @XmlElement(required = true)
    protected String scheme;
    protected Long txnId;
    @XmlElement(required = true)
    protected String contraAccount;
    @XmlElement(required = true, type = Boolean.class, nillable = true)
    protected Boolean reversal;
    @XmlElement(required = true, nillable = true)
    protected UsRole userRole;

    /**
     * Gets the value of the txnRef property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getTxnRef() {
        return txnRef;
    }

    /**
     * Sets the value of the txnRef property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setTxnRef(String value) {
        this.txnRef = value;
    }

    /**
     * Gets the value of the createDate property.
     *
     * @return possible object is {@link XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getCreateDate() {
        return createDate;
    }

    /**
     * Sets the value of the createDate property.
     *
     * @param value allowed object is {@link XMLGregorianCalendar }
     *
     */
    public void setCreateDate(XMLGregorianCalendar value) {
        this.createDate = value;
    }

    /**
     * Gets the value of the employeeId property.
     *
     * @return possible object is {@link Long }
     *
     */
    public Long getEmployeeId() {
        return employeeId;
    }

    /**
     * Sets the value of the employeeId property.
     *
     * @param value allowed object is {@link Long }
     *
     */
    public void setEmployeeId(Long value) {
        this.employeeId = value;
    }

    /**
     * Gets the value of the supervisorId property.
     *
     * @return possible object is {@link Long }
     *
     */
    public Long getSupervisorId() {
        return supervisorId;
    }

    /**
     * Sets the value of the supervisorId property.
     *
     * @param value allowed object is {@link Long }
     *
     */
    public void setSupervisorId(Long value) {
        this.supervisorId = value;
    }

    public BigDecimal getDebitFxRate() {
        return debitFxRate;
    }

    public void setDebitFxRate(BigDecimal debitFxRate) {
        this.debitFxRate = debitFxRate;
    }

    public BigDecimal getCreditFxRate() {
        return creditFxRate;
    }

    public void setCreditFxRate(BigDecimal creditFxRate) {
        this.creditFxRate = creditFxRate;
    }

    /**
     * Gets the value of the transferType property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getTransferType() {
        return transferType;
    }

    /**
     * Sets the value of the transferType property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setTransferType(String value) {
        this.transferType = value;
    }

    /**
     * Gets the value of the currency property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * Sets the value of the currency property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setCurrency(String value) {
        this.currency = value;
    }

    /**
     * Gets the value of the amount property.
     *
     * @return possible object is {@link BigDecimal }
     *
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * Sets the value of the amount property.
     *
     * @param value allowed object is {@link BigDecimal }
     *
     */
    public void setAmount(BigDecimal value) {
        this.amount = value;
    }

    /**
     * Gets the value of the exchangeRate property.
     *
     * @return possible object is {@link BigDecimal }
     *
     */
    public BigDecimal getExchangeRate() {
        return exchangeRate;
    }

    /**
     * Sets the value of the exchangeRate property.
     *
     * @param value allowed object is {@link BigDecimal }
     *
     */
    public void setExchangeRate(BigDecimal value) {
        this.exchangeRate = value;
    }

    /**
     * Gets the value of the receiverBank property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getReceiverBank() {
        return receiverBank;
    }

    /**
     * Sets the value of the receiverBank property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setReceiverBank(String value) {
        this.receiverBank = value;
    }

    /**
     * Gets the value of the receiverAccount property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getReceiverAccount() {
        return receiverAccount;
    }

    /**
     * Sets the value of the receiverAccount property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setReceiverAccount(String value) {
        this.receiverAccount = value;
    }

    /**
     * Gets the value of the receiverName property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getReceiverName() {
        return receiverName;
    }

    /**
     * Sets the value of the receiverName property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setReceiverName(String value) {
        this.receiverName = value;
    }

    /**
     * Gets the value of the senderBank property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getSenderBank() {
        return senderBank;
    }

    /**
     * Sets the value of the senderBank property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setSenderBank(String value) {
        this.senderBank = value;
    }

    /**
     * Gets the value of the senderAccount property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getSenderAccount() {
        return senderAccount;
    }

    /**
     * Sets the value of the senderAccount property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setSenderAccount(String value) {
        this.senderAccount = value;
    }

    /**
     * Gets the value of the senderName property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getSenderName() {
        return senderName;
    }

    /**
     * Sets the value of the senderName property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setSenderName(String value) {
        this.senderName = value;
    }

    /**
     * Gets the value of the description property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the scheme property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getScheme() {
        return scheme;
    }

    /**
     * Sets the value of the scheme property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setScheme(String value) {
        this.scheme = value;
    }

    /**
     * Gets the value of the txnId property.
     *
     * @return possible object is {@link Long }
     *
     */
    public Long getTxnId() {
        return txnId;
    }

    /**
     * Sets the value of the txnId property.
     *
     * @param value allowed object is {@link Long }
     *
     */
    public void setTxnId(Long value) {
        this.txnId = value;
    }

    /**
     * Gets the value of the contraAccount property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getContraAccount() {
        return contraAccount;
    }

    /**
     * Sets the value of the contraAccount property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setContraAccount(String value) {
        this.contraAccount = value;
    }

    /**
     * Gets the value of the reversal property.
     *
     * @return possible object is {@link Boolean }
     *
     */
    public Boolean isReversal() {
        return reversal;
    }

    /**
     * Sets the value of the reversal property.
     *
     * @param value allowed object is {@link Boolean }
     *
     */
    public void setReversal(Boolean value) {
        this.reversal = value;
    }

    /**
     * Gets the value of the userRole property.
     *
     * @return possible object is {@link UsRole }
     *
     */
    public UsRole getUserRole() {
        return userRole;
    }

    /**
     * Sets the value of the userRole property.
     *
     * @param value allowed object is {@link UsRole }
     *
     */
    public void setUserRole(UsRole value) {
        this.userRole = value;
    }

    public XMLGregorianCalendar getValueDate() {
        return valueDate;
    }

    public void setValueDate(XMLGregorianCalendar valueDate) {
        this.valueDate = valueDate;
    }
}
