//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.11 at 09:32:07 PM EAT 
//


package philae.api;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ciType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ciType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Voter_Id"/>
 *     &lt;enumeration value="Employee_Id"/>
 *     &lt;enumeration value="Certificate_Of_Registration"/>
 *     &lt;enumeration value="Valid_Passport"/>
 *     &lt;enumeration value="Valid_Passport_0051"/>
 *     &lt;enumeration value="Driving_Licence"/>
 *     &lt;enumeration value="Deed_Of_Administration"/>
 *     &lt;enumeration value="Letter_Of_Probate"/>
 *     &lt;enumeration value="Student_Id_Card"/>
 *     &lt;enumeration value="National_Id_Card"/>
 *     &lt;enumeration value="Letter_From_Ward_Exec_Officer"/>
 *     &lt;enumeration value="Zanzibari_Id"/>
 *     &lt;enumeration value="Employer_Letter"/>
 *     &lt;enumeration value="Extract_From_Registrar"/>
 *     &lt;enumeration value="Partnership_Deed"/>
 *     &lt;enumeration value="Business_Registration_Certificate"/>
 *     &lt;enumeration value="Valid_Business_Licence"/>
 *     &lt;enumeration value="Memorandum_And_Articles_Of_Association"/>
 *     &lt;enumeration value="Certificate_Of_Incorporation"/>
 *     &lt;enumeration value="Listing_Of_Directors"/>
 *     &lt;enumeration value="Recent_Annual_Returns"/>
 *     &lt;enumeration value="Letter_Of_Introduction"/>
 *     &lt;enumeration value="Corporation_Establishment_Act"/>
 *     &lt;enumeration value="Birth_Certificate"/>
 *     &lt;enumeration value="Tax_Identification_Number"/>
 *     &lt;enumeration value="Bank_Of_Tanzania_Operational_License"/>
 *     &lt;enumeration value="Introduction_Letter"/>
 *     &lt;enumeration value="Valid_Work_Permit"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ciType")
@XmlEnum
public enum CiType implements serializable{

    @XmlEnumValue("Voter_Id")
    VOTER_ID("Voter_Id"),
    @XmlEnumValue("Employee_Id")
    EMPLOYEE_ID("Employee_Id"),
    @XmlEnumValue("Certificate_Of_Registration")
    CERTIFICATE_OF_REGISTRATION("Certificate_Of_Registration"),
    @XmlEnumValue("Valid_Passport")
    VALID_PASSPORT("Valid_Passport"),
    @XmlEnumValue("Valid_Passport_0051")
    VALID_PASSPORT_0051("Valid_Passport_0051"),
    @XmlEnumValue("Driving_Licence")
    DRIVING_LICENCE("Driving_Licence"),
    @XmlEnumValue("Deed_Of_Administration")
    DEED_OF_ADMINISTRATION("Deed_Of_Administration"),
    @XmlEnumValue("Letter_Of_Probate")
    LETTER_OF_PROBATE("Letter_Of_Probate"),
    @XmlEnumValue("Student_Id_Card")
    STUDENT_ID_CARD("Student_Id_Card"),
    @XmlEnumValue("National_Id_Card")
    NATIONAL_ID_CARD("National_Id_Card"),
    @XmlEnumValue("Letter_From_Ward_Exec_Officer")
    LETTER_FROM_WARD_EXEC_OFFICER("Letter_From_Ward_Exec_Officer"),
    @XmlEnumValue("Zanzibari_Id")
    ZANZIBARI_ID("Zanzibari_Id"),
    @XmlEnumValue("Employer_Letter")
    EMPLOYER_LETTER("Employer_Letter"),
    @XmlEnumValue("Extract_From_Registrar")
    EXTRACT_FROM_REGISTRAR("Extract_From_Registrar"),
    @XmlEnumValue("Partnership_Deed")
    PARTNERSHIP_DEED("Partnership_Deed"),
    @XmlEnumValue("Business_Registration_Certificate")
    BUSINESS_REGISTRATION_CERTIFICATE("Business_Registration_Certificate"),
    @XmlEnumValue("Valid_Business_Licence")
    VALID_BUSINESS_LICENCE("Valid_Business_Licence"),
    @XmlEnumValue("Memorandum_And_Articles_Of_Association")
    MEMORANDUM_AND_ARTICLES_OF_ASSOCIATION("Memorandum_And_Articles_Of_Association"),
    @XmlEnumValue("Certificate_Of_Incorporation")
    CERTIFICATE_OF_INCORPORATION("Certificate_Of_Incorporation"),
    @XmlEnumValue("Listing_Of_Directors")
    LISTING_OF_DIRECTORS("Listing_Of_Directors"),
    @XmlEnumValue("Recent_Annual_Returns")
    RECENT_ANNUAL_RETURNS("Recent_Annual_Returns"),
    @XmlEnumValue("Letter_Of_Introduction")
    LETTER_OF_INTRODUCTION("Letter_Of_Introduction"),
    @XmlEnumValue("Corporation_Establishment_Act")
    CORPORATION_ESTABLISHMENT_ACT("Corporation_Establishment_Act"),
    @XmlEnumValue("Birth_Certificate")
    BIRTH_CERTIFICATE("Birth_Certificate"),
    @XmlEnumValue("Tax_Identification_Number")
    TAX_IDENTIFICATION_NUMBER("Tax_Identification_Number"),
    @XmlEnumValue("Bank_Of_Tanzania_Operational_License")
    BANK_OF_TANZANIA_OPERATIONAL_LICENSE("Bank_Of_Tanzania_Operational_License"),
    @XmlEnumValue("Introduction_Letter")
    INTRODUCTION_LETTER("Introduction_Letter"),
    @XmlEnumValue("Valid_Work_Permit")
    VALID_WORK_PERMIT("Valid_Work_Permit");
    private final String value;

    CiType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static CiType fromValue(String v) {
        for (CiType c: CiType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
