//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.11 at 09:32:07 PM EAT 
//


package philae.api;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for cuTitle.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="cuTitle">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Mr"/>
 *     &lt;enumeration value="Alhaji"/>
 *     &lt;enumeration value="Dr"/>
 *     &lt;enumeration value="Miss"/>
 *     &lt;enumeration value="Mrs"/>
 *     &lt;enumeration value="Professor"/>
 *     &lt;enumeration value="Rev"/>
 *     &lt;enumeration value="Ms"/>
 *     &lt;enumeration value="Apostle"/>
 *     &lt;enumeration value="Apostress"/>
 *     &lt;enumeration value="Justice"/>
 *     &lt;enumeration value="Engineer"/>
 *     &lt;enumeration value="Ndugu"/>
 *     &lt;enumeration value="Honourable"/>
 *     &lt;enumeration value="Ambassador"/>
 *     &lt;enumeration value="Mheshimiwa"/>
 *     &lt;enumeration value="Sir"/>
 *     &lt;enumeration value="Hajjat"/>
 *     &lt;enumeration value="Other"/>
 *     &lt;enumeration value="Father"/>
 *     &lt;enumeration value="Bishop"/>
 *     &lt;enumeration value="Monsr"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "cuTitle")
@XmlEnum
public enum CuTitle implements serializable {

    @XmlEnumValue("Mr")
    MR("Mr"),
    @XmlEnumValue("Alhaji")
    ALHAJI("Alhaji"),
    @XmlEnumValue("Dr")
    DR("Dr"),
    @XmlEnumValue("Miss")
    MISS("Miss"),
    @XmlEnumValue("Mrs")
    MRS("Mrs"),
    @XmlEnumValue("Professor")
    PROFESSOR("Professor"),
    @XmlEnumValue("Rev")
    REV("Rev"),
    @XmlEnumValue("Ms")
    MS("Ms"),
    @XmlEnumValue("Apostle")
    APOSTLE("Apostle"),
    @XmlEnumValue("Apostress")
    APOSTRESS("Apostress"),
    @XmlEnumValue("Justice")
    JUSTICE("Justice"),
    @XmlEnumValue("Engineer")
    ENGINEER("Engineer"),
    @XmlEnumValue("Ndugu")
    NDUGU("Ndugu"),
    @XmlEnumValue("Honourable")
    HONOURABLE("Honourable"),
    @XmlEnumValue("Ambassador")
    AMBASSADOR("Ambassador"),
    @XmlEnumValue("Mheshimiwa")
    MHESHIMIWA("Mheshimiwa"),
    @XmlEnumValue("Sir")
    SIR("Sir"),
    @XmlEnumValue("Hajjat")
    HAJJAT("Hajjat"),
    @XmlEnumValue("Other")
    OTHER("Other"),
    @XmlEnumValue("Father")
    FATHER("Father"),
    @XmlEnumValue("Bishop")
    BISHOP("Bishop"),
    @XmlEnumValue("Monsr")
    MONSR("Monsr");
    private final String value;

    CuTitle(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static CuTitle fromValue(String v) {
        for (CuTitle c: CuTitle.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
