//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.11 at 09:32:07 PM EAT 
//


package philae.api;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for cuType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="cuType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Individual"/>
 *     &lt;enumeration value="Institutions"/>
 *     &lt;enumeration value="Bank_Current_Accounts"/>
 *     &lt;enumeration value="Informal_Groups"/>
 *     &lt;enumeration value="Staff"/>
 *     &lt;enumeration value="Joint"/>
 *     &lt;enumeration value="Trade_Finance_Non_Customer"/>
 *     &lt;enumeration value="Minor"/>
 *     &lt;enumeration value="Companies"/>
 *     &lt;enumeration value="Student"/>
 *     &lt;enumeration value="Sole_Proprietor_Corporate"/>
 *     &lt;enumeration value="Agent_Corporate"/>
 *     &lt;enumeration value="Partnership_Corporate"/>
 *     &lt;enumeration value="Collection_Agents"/>
 *     &lt;enumeration value="Bank_Nostro_Accounts"/>
 *     &lt;enumeration value="Government"/>
 *     &lt;enumeration value="Trustees"/>
 *     &lt;enumeration value="Schools_Colleges"/>
 *     &lt;enumeration value="Political_Parties"/>
 *     &lt;enumeration value="Embassies_Foreign_Missions"/>
 *     &lt;enumeration value="Informal_Associations_Clubs_Societies"/>
 *     &lt;enumeration value="Formal_Associations_Clubs_Societies"/>
 *     &lt;enumeration value="Formal_Group"/>
 *     &lt;enumeration value="Sole_Proprietor"/>
 *     &lt;enumeration value="Agent_Personal"/>
 *     &lt;enumeration value="Partnership_Personal"/>
 *     &lt;enumeration value="Counterpart_Banks"/>
 *     &lt;enumeration value="Migration_Minor_"/>
 *     &lt;enumeration value="Pamoja_Customers"/>
 *     &lt;enumeration value="Individual_TBCL"/>
 *     &lt;enumeration value="Association_TBCL"/>
 *     &lt;enumeration value="Companies_TBCL"/>
 *     &lt;enumeration value="Partnership_Corporate_TBCL"/>
 *     &lt;enumeration value="Sole_Proprietor_Personal_TBCL"/>
 *     &lt;enumeration value="Sole_Proprietor_Corporate_TBCL"/>
 *     &lt;enumeration value="Special_Fixed_Deposit_Customer"/>
 *     &lt;enumeration value="Group_TBCL"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "cuType")
@XmlEnum
public enum CuType implements serializable{

    @XmlEnumValue("Individual")
    INDIVIDUAL("Individual"),
    @XmlEnumValue("Institutions")
    INSTITUTIONS("Institutions"),
    @XmlEnumValue("Bank_Current_Accounts")
    BANK_CURRENT_ACCOUNTS("Bank_Current_Accounts"),
    @XmlEnumValue("Informal_Groups")
    INFORMAL_GROUPS("Informal_Groups"),
    @XmlEnumValue("Staff")
    STAFF("Staff"),
    @XmlEnumValue("Joint")
    JOINT("Joint"),
    @XmlEnumValue("Trade_Finance_Non_Customer")
    TRADE_FINANCE_NON_CUSTOMER("Trade_Finance_Non_Customer"),
    @XmlEnumValue("Minor")
    MINOR("Minor"),
    @XmlEnumValue("Companies")
    COMPANIES("Companies"),
    @XmlEnumValue("Student")
    STUDENT("Student"),
    @XmlEnumValue("Sole_Proprietor_Corporate")
    SOLE_PROPRIETOR_CORPORATE("Sole_Proprietor_Corporate"),
    @XmlEnumValue("Agent_Corporate")
    AGENT_CORPORATE("Agent_Corporate"),
    @XmlEnumValue("Partnership_Corporate")
    PARTNERSHIP_CORPORATE("Partnership_Corporate"),
    @XmlEnumValue("Collection_Agents")
    COLLECTION_AGENTS("Collection_Agents"),
    @XmlEnumValue("Bank_Nostro_Accounts")
    BANK_NOSTRO_ACCOUNTS("Bank_Nostro_Accounts"),
    @XmlEnumValue("Government")
    GOVERNMENT("Government"),
    @XmlEnumValue("Trustees")
    TRUSTEES("Trustees"),
    @XmlEnumValue("Schools_Colleges")
    SCHOOLS_COLLEGES("Schools_Colleges"),
    @XmlEnumValue("Political_Parties")
    POLITICAL_PARTIES("Political_Parties"),
    @XmlEnumValue("Embassies_Foreign_Missions")
    EMBASSIES_FOREIGN_MISSIONS("Embassies_Foreign_Missions"),
    @XmlEnumValue("Informal_Associations_Clubs_Societies")
    INFORMAL_ASSOCIATIONS_CLUBS_SOCIETIES("Informal_Associations_Clubs_Societies"),
    @XmlEnumValue("Formal_Associations_Clubs_Societies")
    FORMAL_ASSOCIATIONS_CLUBS_SOCIETIES("Formal_Associations_Clubs_Societies"),
    @XmlEnumValue("Formal_Group")
    FORMAL_GROUP("Formal_Group"),
    @XmlEnumValue("Sole_Proprietor")
    SOLE_PROPRIETOR("Sole_Proprietor"),
    @XmlEnumValue("Agent_Personal")
    AGENT_PERSONAL("Agent_Personal"),
    @XmlEnumValue("Partnership_Personal")
    PARTNERSHIP_PERSONAL("Partnership_Personal"),
    @XmlEnumValue("Counterpart_Banks")
    COUNTERPART_BANKS("Counterpart_Banks"),
    @XmlEnumValue("Migration_Minor_")
    MIGRATION_MINOR("Migration_Minor_"),
    @XmlEnumValue("Pamoja_Customers")
    PAMOJA_CUSTOMERS("Pamoja_Customers"),
    @XmlEnumValue("Individual_TBCL")
    INDIVIDUAL_TBCL("Individual_TBCL"),
    @XmlEnumValue("Association_TBCL")
    ASSOCIATION_TBCL("Association_TBCL"),
    @XmlEnumValue("Companies_TBCL")
    COMPANIES_TBCL("Companies_TBCL"),
    @XmlEnumValue("Partnership_Corporate_TBCL")
    PARTNERSHIP_CORPORATE_TBCL("Partnership_Corporate_TBCL"),
    @XmlEnumValue("Sole_Proprietor_Personal_TBCL")
    SOLE_PROPRIETOR_PERSONAL_TBCL("Sole_Proprietor_Personal_TBCL"),
    @XmlEnumValue("Sole_Proprietor_Corporate_TBCL")
    SOLE_PROPRIETOR_CORPORATE_TBCL("Sole_Proprietor_Corporate_TBCL"),
    @XmlEnumValue("Special_Fixed_Deposit_Customer")
    SPECIAL_FIXED_DEPOSIT_CUSTOMER("Special_Fixed_Deposit_Customer"),
    @XmlEnumValue("Group_TBCL")
    GROUP_TBCL("Group_TBCL");
    private final String value;

    CuType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static CuType fromValue(String v) {
        for (CuType c: CuType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
