//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.11 at 09:32:07 PM EAT 
//


package philae.api;

import java.math.BigDecimal;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for dhRecord complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="dhRecord">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="acctAmt" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="acctCrncyCdIso" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="acctHistId" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="acctNo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="buNm" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="channelDesc" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="channelId" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="chqNo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="depositorPayeeNm" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="drCrInd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="eventCd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="originBuId" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="revTranJournalId" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="revTxnFg" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="stmntBal" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="sysCreateTs" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="tranDesc" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="tranDt" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="tranJournalId" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="tranRefTxt" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="txnContraAcctNo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="valueDt" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "dhRecord", propOrder = {
    "acctAmt",
    "acctCrncyCdIso",
    "acctHistId",
    "acctNo",
    "buNm",
    "channelDesc",
    "channelId",
    "chqNo",
    "depositorPayeeNm",
    "drCrInd",
    "eventCd",
    "originBuId",
    "revTranJournalId",
    "revTxnFg",
    "stmntBal",
    "sysCreateTs",
    "tranDesc",
    "tranDt",
    "tranJournalId",
    "tranRefTxt",
    "txnContraAcctNo",
    "valueDt"
})
public class DhRecord implements serializable{

    protected BigDecimal acctAmt;
    protected String acctCrncyCdIso;
    protected Long acctHistId;
    protected String acctNo;
    protected String buNm;
    protected String channelDesc;
    protected Long channelId;
    protected String chqNo;
    protected String depositorPayeeNm;
    protected String drCrInd;
    protected String eventCd;
    protected Long originBuId;
    protected Long revTranJournalId;
    protected String revTxnFg;
    protected BigDecimal stmntBal;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar sysCreateTs;
    protected String tranDesc;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar tranDt;
    protected Long tranJournalId;
    protected String tranRefTxt;
    protected String txnContraAcctNo;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar valueDt;

    /**
     * Gets the value of the acctAmt property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAcctAmt() {
        return acctAmt;
    }

    /**
     * Sets the value of the acctAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAcctAmt(BigDecimal value) {
        this.acctAmt = value;
    }

    /**
     * Gets the value of the acctCrncyCdIso property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAcctCrncyCdIso() {
        return acctCrncyCdIso;
    }

    /**
     * Sets the value of the acctCrncyCdIso property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAcctCrncyCdIso(String value) {
        this.acctCrncyCdIso = value;
    }

    /**
     * Gets the value of the acctHistId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getAcctHistId() {
        return acctHistId;
    }

    /**
     * Sets the value of the acctHistId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setAcctHistId(Long value) {
        this.acctHistId = value;
    }

    /**
     * Gets the value of the acctNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAcctNo() {
        return acctNo;
    }

    /**
     * Sets the value of the acctNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAcctNo(String value) {
        this.acctNo = value;
    }

    /**
     * Gets the value of the buNm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBuNm() {
        return buNm;
    }

    /**
     * Sets the value of the buNm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBuNm(String value) {
        this.buNm = value;
    }

    /**
     * Gets the value of the channelDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChannelDesc() {
        return channelDesc;
    }

    /**
     * Sets the value of the channelDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChannelDesc(String value) {
        this.channelDesc = value;
    }

    /**
     * Gets the value of the channelId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getChannelId() {
        return channelId;
    }

    /**
     * Sets the value of the channelId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setChannelId(Long value) {
        this.channelId = value;
    }

    /**
     * Gets the value of the chqNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChqNo() {
        return chqNo;
    }

    /**
     * Sets the value of the chqNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChqNo(String value) {
        this.chqNo = value;
    }

    /**
     * Gets the value of the depositorPayeeNm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDepositorPayeeNm() {
        return depositorPayeeNm;
    }

    /**
     * Sets the value of the depositorPayeeNm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDepositorPayeeNm(String value) {
        this.depositorPayeeNm = value;
    }

    /**
     * Gets the value of the drCrInd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDrCrInd() {
        return drCrInd;
    }

    /**
     * Sets the value of the drCrInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDrCrInd(String value) {
        this.drCrInd = value;
    }

    /**
     * Gets the value of the eventCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEventCd() {
        return eventCd;
    }

    /**
     * Sets the value of the eventCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEventCd(String value) {
        this.eventCd = value;
    }

    /**
     * Gets the value of the originBuId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getOriginBuId() {
        return originBuId;
    }

    /**
     * Sets the value of the originBuId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setOriginBuId(Long value) {
        this.originBuId = value;
    }

    /**
     * Gets the value of the revTranJournalId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getRevTranJournalId() {
        return revTranJournalId;
    }

    /**
     * Sets the value of the revTranJournalId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setRevTranJournalId(Long value) {
        this.revTranJournalId = value;
    }

    /**
     * Gets the value of the revTxnFg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRevTxnFg() {
        return revTxnFg;
    }

    /**
     * Sets the value of the revTxnFg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRevTxnFg(String value) {
        this.revTxnFg = value;
    }

    /**
     * Gets the value of the stmntBal property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getStmntBal() {
        return stmntBal;
    }

    /**
     * Sets the value of the stmntBal property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setStmntBal(BigDecimal value) {
        this.stmntBal = value;
    }

    /**
     * Gets the value of the sysCreateTs property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getSysCreateTs() {
        return sysCreateTs;
    }

    /**
     * Sets the value of the sysCreateTs property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setSysCreateTs(XMLGregorianCalendar value) {
        this.sysCreateTs = value;
    }

    /**
     * Gets the value of the tranDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTranDesc() {
        return tranDesc;
    }

    /**
     * Sets the value of the tranDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTranDesc(String value) {
        this.tranDesc = value;
    }

    /**
     * Gets the value of the tranDt property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTranDt() {
        return tranDt;
    }

    /**
     * Sets the value of the tranDt property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTranDt(XMLGregorianCalendar value) {
        this.tranDt = value;
    }

    /**
     * Gets the value of the tranJournalId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getTranJournalId() {
        return tranJournalId;
    }

    /**
     * Sets the value of the tranJournalId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setTranJournalId(Long value) {
        this.tranJournalId = value;
    }

    /**
     * Gets the value of the tranRefTxt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTranRefTxt() {
        return tranRefTxt;
    }

    /**
     * Sets the value of the tranRefTxt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTranRefTxt(String value) {
        this.tranRefTxt = value;
    }

    /**
     * Gets the value of the txnContraAcctNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTxnContraAcctNo() {
        return txnContraAcctNo;
    }

    /**
     * Sets the value of the txnContraAcctNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTxnContraAcctNo(String value) {
        this.txnContraAcctNo = value;
    }

    /**
     * Gets the value of the valueDt property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getValueDt() {
        return valueDt;
    }

    /**
     * Sets the value of the valueDt property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setValueDt(XMLGregorianCalendar value) {
        this.valueDt = value;
    }

}
