//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.11 at 09:32:07 PM EAT 
//


package philae.api;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the philae.api package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _QueryDepositBalanceResponse_QNAME = new QName("http://api.PHilae/", "queryDepositBalanceResponse");
    private final static QName _PostDepositToGLTransfer_QNAME = new QName("http://api.PHilae/", "postDepositToGLTransfer");
    private final static QName _EnrollMobileChannelUserResponse_QNAME = new QName("http://api.PHilae/", "enrollMobileChannelUserResponse");
    private final static QName _PostGLToGLTransfer_QNAME = new QName("http://api.PHilae/", "postGLToGLTransfer");
    private final static QName _QueryDepositBalance_QNAME = new QName("http://api.PHilae/", "queryDepositBalance");
    private final static QName _QueryDepositHistory_QNAME = new QName("http://api.PHilae/", "queryDepositHistory");
    private final static QName _CreateDepositAccount_QNAME = new QName("http://api.PHilae/", "createDepositAccount");
    private final static QName _CreateCustomerResponse_QNAME = new QName("http://api.PHilae/", "createCustomerResponse");
    private final static QName _CreateCustomer_QNAME = new QName("http://api.PHilae/", "createCustomer");
    private final static QName _PostTransferPaymentResponse_QNAME = new QName("http://api.PHilae/", "postTransferPaymentResponse");
    private final static QName _QueryDepositHistoryResponse_QNAME = new QName("http://api.PHilae/", "queryDepositHistoryResponse");
    private final static QName _ActivateDepositAccount_QNAME = new QName("http://api.PHilae/", "activateDepositAccount");
    private final static QName _PostCashPayment_QNAME = new QName("http://api.PHilae/", "postCashPayment");
    private final static QName _PostGLToDepositTransfer_QNAME = new QName("http://api.PHilae/", "postGLToDepositTransfer");
    private final static QName _LoginUser_QNAME = new QName("http://api.PHilae/", "loginUser");
    private final static QName _PostTransferPayment_QNAME = new QName("http://api.PHilae/", "postTransferPayment");
    private final static QName _ActivateDepositAccountResponse_QNAME = new QName("http://api.PHilae/", "activateDepositAccountResponse");
    private final static QName _PostGLToGLTransferResponse_QNAME = new QName("http://api.PHilae/", "postGLToGLTransferResponse");
    private final static QName _QueryGLHistory_QNAME = new QName("http://api.PHilae/", "queryGLHistory");
    private final static QName _QueryGLHistoryResponse_QNAME = new QName("http://api.PHilae/", "queryGLHistoryResponse");
    private final static QName _CreateDepositAccountResponse_QNAME = new QName("http://api.PHilae/", "createDepositAccountResponse");
    private final static QName _PostCashPaymentResponse_QNAME = new QName("http://api.PHilae/", "postCashPaymentResponse");
    private final static QName _PostCashWithdrawalResponse_QNAME = new QName("http://api.PHilae/", "postCashWithdrawalResponse");
    private final static QName _PostGLToDepositTransferResponse_QNAME = new QName("http://api.PHilae/", "postGLToDepositTransferResponse");
    private final static QName _LoginUserResponse_QNAME = new QName("http://api.PHilae/", "loginUserResponse");
    private final static QName _PostDepositToGLTransferResponse_QNAME = new QName("http://api.PHilae/", "postDepositToGLTransferResponse");
    private final static QName _EnrollMobileChannelUser_QNAME = new QName("http://api.PHilae/", "enrollMobileChannelUser");
    private final static QName _PostCashWithdrawal_QNAME = new QName("http://api.PHilae/", "postCashWithdrawal");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: philae.api
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DhResponse }
     * 
     */
    public DhResponse createDhResponse() {
        return new DhResponse();
    }

    /**
     * Create an instance of {@link BnUser }
     * 
     */
    public BnUser createBnUser() {
        return new BnUser();
    }

    /**
     * Create an instance of {@link TlDrawer }
     * 
     */
    public TlDrawer createTlDrawer() {
        return new TlDrawer();
    }

    /**
     * Create an instance of {@link UsRole }
     * 
     */
    public UsRole createUsRole() {
        return new UsRole();
    }

    /**
     * Create an instance of {@link LhResponse }
     * 
     */
    public LhResponse createLhResponse() {
        return new LhResponse();
    }

    /**
     * Create an instance of {@link CreateDepositAccountResponse }
     * 
     */
    public CreateDepositAccountResponse createCreateDepositAccountResponse() {
        return new CreateDepositAccountResponse();
    }

    /**
     * Create an instance of {@link LoginUserResponse }
     * 
     */
    public LoginUserResponse createLoginUserResponse() {
        return new LoginUserResponse();
    }

    /**
     * Create an instance of {@link PostDepositToGLTransferResponse }
     * 
     */
    public PostDepositToGLTransferResponse createPostDepositToGLTransferResponse() {
        return new PostDepositToGLTransferResponse();
    }

    /**
     * Create an instance of {@link PostCashWithdrawalResponse }
     * 
     */
    public PostCashWithdrawalResponse createPostCashWithdrawalResponse() {
        return new PostCashWithdrawalResponse();
    }

    /**
     * Create an instance of {@link PostGLToDepositTransferResponse }
     * 
     */
    public PostGLToDepositTransferResponse createPostGLToDepositTransferResponse() {
        return new PostGLToDepositTransferResponse();
    }

    /**
     * Create an instance of {@link PostCashPaymentResponse }
     * 
     */
    public PostCashPaymentResponse createPostCashPaymentResponse() {
        return new PostCashPaymentResponse();
    }

    /**
     * Create an instance of {@link PostCashWithdrawal }
     * 
     */
    public PostCashWithdrawal createPostCashWithdrawal() {
        return new PostCashWithdrawal();
    }

    /**
     * Create an instance of {@link EnrollMobileChannelUser }
     * 
     */
    public EnrollMobileChannelUser createEnrollMobileChannelUser() {
        return new EnrollMobileChannelUser();
    }

    /**
     * Create an instance of {@link PostTransferPayment }
     * 
     */
    public PostTransferPayment createPostTransferPayment() {
        return new PostTransferPayment();
    }

    /**
     * Create an instance of {@link LoginUser }
     * 
     */
    public LoginUser createLoginUser() {
        return new LoginUser();
    }

    /**
     * Create an instance of {@link PostGLToDepositTransfer }
     * 
     */
    public PostGLToDepositTransfer createPostGLToDepositTransfer() {
        return new PostGLToDepositTransfer();
    }

    /**
     * Create an instance of {@link PostGLToGLTransferResponse }
     * 
     */
    public PostGLToGLTransferResponse createPostGLToGLTransferResponse() {
        return new PostGLToGLTransferResponse();
    }

    /**
     * Create an instance of {@link ActivateDepositAccountResponse }
     * 
     */
    public ActivateDepositAccountResponse createActivateDepositAccountResponse() {
        return new ActivateDepositAccountResponse();
    }

    /**
     * Create an instance of {@link QueryGLHistory }
     * 
     */
    public QueryGLHistory createQueryGLHistory() {
        return new QueryGLHistory();
    }

    /**
     * Create an instance of {@link QueryGLHistoryResponse }
     * 
     */
    public QueryGLHistoryResponse createQueryGLHistoryResponse() {
        return new QueryGLHistoryResponse();
    }

    /**
     * Create an instance of {@link CreateDepositAccount }
     * 
     */
    public CreateDepositAccount createCreateDepositAccount() {
        return new CreateDepositAccount();
    }

    /**
     * Create an instance of {@link QueryDepositBalance }
     * 
     */
    public QueryDepositBalance createQueryDepositBalance() {
        return new QueryDepositBalance();
    }

    /**
     * Create an instance of {@link QueryDepositHistory }
     * 
     */
    public QueryDepositHistory createQueryDepositHistory() {
        return new QueryDepositHistory();
    }

    /**
     * Create an instance of {@link CreateCustomer }
     * 
     */
    public CreateCustomer createCreateCustomer() {
        return new CreateCustomer();
    }

    /**
     * Create an instance of {@link PostTransferPaymentResponse }
     * 
     */
    public PostTransferPaymentResponse createPostTransferPaymentResponse() {
        return new PostTransferPaymentResponse();
    }

    /**
     * Create an instance of {@link CreateCustomerResponse }
     * 
     */
    public CreateCustomerResponse createCreateCustomerResponse() {
        return new CreateCustomerResponse();
    }

    /**
     * Create an instance of {@link QueryDepositHistoryResponse }
     * 
     */
    public QueryDepositHistoryResponse createQueryDepositHistoryResponse() {
        return new QueryDepositHistoryResponse();
    }

    /**
     * Create an instance of {@link PostCashPayment }
     * 
     */
    public PostCashPayment createPostCashPayment() {
        return new PostCashPayment();
    }

    /**
     * Create an instance of {@link ActivateDepositAccount }
     * 
     */
    public ActivateDepositAccount createActivateDepositAccount() {
        return new ActivateDepositAccount();
    }

    /**
     * Create an instance of {@link PostDepositToGLTransfer }
     * 
     */
    public PostDepositToGLTransfer createPostDepositToGLTransfer() {
        return new PostDepositToGLTransfer();
    }

    /**
     * Create an instance of {@link QueryDepositBalanceResponse }
     * 
     */
    public QueryDepositBalanceResponse createQueryDepositBalanceResponse() {
        return new QueryDepositBalanceResponse();
    }

    /**
     * Create an instance of {@link EnrollMobileChannelUserResponse }
     * 
     */
    public EnrollMobileChannelUserResponse createEnrollMobileChannelUserResponse() {
        return new EnrollMobileChannelUserResponse();
    }

    /**
     * Create an instance of {@link PostGLToGLTransfer }
     * 
     */
    public PostGLToGLTransfer createPostGLToGLTransfer() {
        return new PostGLToGLTransfer();
    }

    /**
     * Create an instance of {@link CaRequest }
     * 
     */
    public CaRequest createCaRequest() {
        return new CaRequest();
    }

    /**
     * Create an instance of {@link AaRequest }
     * 
     */
    public AaRequest createAaRequest() {
        return new AaRequest();
    }

    /**
     * Create an instance of {@link XaRequest }
     * 
     */
    public XaRequest createXaRequest() {
        return new XaRequest();
    }

    /**
     * Create an instance of {@link LhRequest }
     * 
     */
    public LhRequest createLhRequest() {
        return new LhRequest();
    }

    /**
     * Create an instance of {@link CcRequest }
     * 
     */
    public CcRequest createCcRequest() {
        return new CcRequest();
    }

    /**
     * Create an instance of {@link XaResponse }
     * 
     */
    public XaResponse createXaResponse() {
        return new XaResponse();
    }

    /**
     * Create an instance of {@link CcResponse }
     * 
     */
    public CcResponse createCcResponse() {
        return new CcResponse();
    }

    /**
     * Create an instance of {@link UlRequest }
     * 
     */
    public UlRequest createUlRequest() {
        return new UlRequest();
    }

    /**
     * Create an instance of {@link UrLimit }
     * 
     */
    public UrLimit createUrLimit() {
        return new UrLimit();
    }

    /**
     * Create an instance of {@link DhRequest }
     * 
     */
    public DhRequest createDhRequest() {
        return new DhRequest();
    }

    /**
     * Create an instance of {@link CaResponse }
     * 
     */
    public CaResponse createCaResponse() {
        return new CaResponse();
    }

    /**
     * Create an instance of {@link CuRequest }
     * 
     */
    public CuRequest createCuRequest() {
        return new CuRequest();
    }

    /**
     * Create an instance of {@link BlRequest }
     * 
     */
    public BlRequest createBlRequest() {
        return new BlRequest();
    }

    /**
     * Create an instance of {@link DhRecord }
     * 
     */
    public DhRecord createDhRecord() {
        return new DhRecord();
    }

    /**
     * Create an instance of {@link LhRecord }
     * 
     */
    public LhRecord createLhRecord() {
        return new LhRecord();
    }

    /**
     * Create an instance of {@link CpRequest }
     * 
     */
    public CpRequest createCpRequest() {
        return new CpRequest();
    }

    /**
     * Create an instance of {@link CnCurrency }
     * 
     */
    public CnCurrency createCnCurrency() {
        return new CnCurrency();
    }

    /**
     * Create an instance of {@link UlResponse }
     * 
     */
    public UlResponse createUlResponse() {
        return new UlResponse();
    }

    /**
     * Create an instance of {@link TxRequest }
     * 
     */
    public TxRequest createTxRequest() {
        return new TxRequest();
    }

    /**
     * Create an instance of {@link TpRequest }
     * 
     */
    public TpRequest createTpRequest() {
        return new TpRequest();
    }

    /**
     * Create an instance of {@link DhResponse.Records }
     * 
     */
    public DhResponse.Records createDhResponseRecords() {
        return new DhResponse.Records();
    }

    /**
     * Create an instance of {@link BnUser.Roles }
     * 
     */
    public BnUser.Roles createBnUserRoles() {
        return new BnUser.Roles();
    }

    /**
     * Create an instance of {@link TlDrawer.Currencies }
     * 
     */
    public TlDrawer.Currencies createTlDrawerCurrencies() {
        return new TlDrawer.Currencies();
    }

    /**
     * Create an instance of {@link UsRole.Limits }
     * 
     */
    public UsRole.Limits createUsRoleLimits() {
        return new UsRole.Limits();
    }

    /**
     * Create an instance of {@link UsRole.Drawers }
     * 
     */
    public UsRole.Drawers createUsRoleDrawers() {
        return new UsRole.Drawers();
    }

    /**
     * Create an instance of {@link LhResponse.Records }
     * 
     */
    public LhResponse.Records createLhResponseRecords() {
        return new LhResponse.Records();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QueryDepositBalanceResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://api.PHilae/", name = "queryDepositBalanceResponse")
    public JAXBElement<QueryDepositBalanceResponse> createQueryDepositBalanceResponse(QueryDepositBalanceResponse value) {
        return new JAXBElement<QueryDepositBalanceResponse>(_QueryDepositBalanceResponse_QNAME, QueryDepositBalanceResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PostDepositToGLTransfer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://api.PHilae/", name = "postDepositToGLTransfer")
    public JAXBElement<PostDepositToGLTransfer> createPostDepositToGLTransfer(PostDepositToGLTransfer value) {
        return new JAXBElement<PostDepositToGLTransfer>(_PostDepositToGLTransfer_QNAME, PostDepositToGLTransfer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EnrollMobileChannelUserResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://api.PHilae/", name = "enrollMobileChannelUserResponse")
    public JAXBElement<EnrollMobileChannelUserResponse> createEnrollMobileChannelUserResponse(EnrollMobileChannelUserResponse value) {
        return new JAXBElement<EnrollMobileChannelUserResponse>(_EnrollMobileChannelUserResponse_QNAME, EnrollMobileChannelUserResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PostGLToGLTransfer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://api.PHilae/", name = "postGLToGLTransfer")
    public JAXBElement<PostGLToGLTransfer> createPostGLToGLTransfer(PostGLToGLTransfer value) {
        return new JAXBElement<PostGLToGLTransfer>(_PostGLToGLTransfer_QNAME, PostGLToGLTransfer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QueryDepositBalance }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://api.PHilae/", name = "queryDepositBalance")
    public JAXBElement<QueryDepositBalance> createQueryDepositBalance(QueryDepositBalance value) {
        return new JAXBElement<QueryDepositBalance>(_QueryDepositBalance_QNAME, QueryDepositBalance.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QueryDepositHistory }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://api.PHilae/", name = "queryDepositHistory")
    public JAXBElement<QueryDepositHistory> createQueryDepositHistory(QueryDepositHistory value) {
        return new JAXBElement<QueryDepositHistory>(_QueryDepositHistory_QNAME, QueryDepositHistory.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CreateDepositAccount }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://api.PHilae/", name = "createDepositAccount")
    public JAXBElement<CreateDepositAccount> createCreateDepositAccount(CreateDepositAccount value) {
        return new JAXBElement<CreateDepositAccount>(_CreateDepositAccount_QNAME, CreateDepositAccount.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CreateCustomerResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://api.PHilae/", name = "createCustomerResponse")
    public JAXBElement<CreateCustomerResponse> createCreateCustomerResponse(CreateCustomerResponse value) {
        return new JAXBElement<CreateCustomerResponse>(_CreateCustomerResponse_QNAME, CreateCustomerResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CreateCustomer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://api.PHilae/", name = "createCustomer")
    public JAXBElement<CreateCustomer> createCreateCustomer(CreateCustomer value) {
        return new JAXBElement<CreateCustomer>(_CreateCustomer_QNAME, CreateCustomer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PostTransferPaymentResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://api.PHilae/", name = "postTransferPaymentResponse")
    public JAXBElement<PostTransferPaymentResponse> createPostTransferPaymentResponse(PostTransferPaymentResponse value) {
        return new JAXBElement<PostTransferPaymentResponse>(_PostTransferPaymentResponse_QNAME, PostTransferPaymentResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QueryDepositHistoryResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://api.PHilae/", name = "queryDepositHistoryResponse")
    public JAXBElement<QueryDepositHistoryResponse> createQueryDepositHistoryResponse(QueryDepositHistoryResponse value) {
        return new JAXBElement<QueryDepositHistoryResponse>(_QueryDepositHistoryResponse_QNAME, QueryDepositHistoryResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ActivateDepositAccount }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://api.PHilae/", name = "activateDepositAccount")
    public JAXBElement<ActivateDepositAccount> createActivateDepositAccount(ActivateDepositAccount value) {
        return new JAXBElement<ActivateDepositAccount>(_ActivateDepositAccount_QNAME, ActivateDepositAccount.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PostCashPayment }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://api.PHilae/", name = "postCashPayment")
    public JAXBElement<PostCashPayment> createPostCashPayment(PostCashPayment value) {
        return new JAXBElement<PostCashPayment>(_PostCashPayment_QNAME, PostCashPayment.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PostGLToDepositTransfer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://api.PHilae/", name = "postGLToDepositTransfer")
    public JAXBElement<PostGLToDepositTransfer> createPostGLToDepositTransfer(PostGLToDepositTransfer value) {
        return new JAXBElement<PostGLToDepositTransfer>(_PostGLToDepositTransfer_QNAME, PostGLToDepositTransfer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LoginUser }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://api.PHilae/", name = "loginUser")
    public JAXBElement<LoginUser> createLoginUser(LoginUser value) {
        return new JAXBElement<LoginUser>(_LoginUser_QNAME, LoginUser.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PostTransferPayment }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://api.PHilae/", name = "postTransferPayment")
    public JAXBElement<PostTransferPayment> createPostTransferPayment(PostTransferPayment value) {
        return new JAXBElement<PostTransferPayment>(_PostTransferPayment_QNAME, PostTransferPayment.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ActivateDepositAccountResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://api.PHilae/", name = "activateDepositAccountResponse")
    public JAXBElement<ActivateDepositAccountResponse> createActivateDepositAccountResponse(ActivateDepositAccountResponse value) {
        return new JAXBElement<ActivateDepositAccountResponse>(_ActivateDepositAccountResponse_QNAME, ActivateDepositAccountResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PostGLToGLTransferResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://api.PHilae/", name = "postGLToGLTransferResponse")
    public JAXBElement<PostGLToGLTransferResponse> createPostGLToGLTransferResponse(PostGLToGLTransferResponse value) {
        return new JAXBElement<PostGLToGLTransferResponse>(_PostGLToGLTransferResponse_QNAME, PostGLToGLTransferResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QueryGLHistory }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://api.PHilae/", name = "queryGLHistory")
    public JAXBElement<QueryGLHistory> createQueryGLHistory(QueryGLHistory value) {
        return new JAXBElement<QueryGLHistory>(_QueryGLHistory_QNAME, QueryGLHistory.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QueryGLHistoryResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://api.PHilae/", name = "queryGLHistoryResponse")
    public JAXBElement<QueryGLHistoryResponse> createQueryGLHistoryResponse(QueryGLHistoryResponse value) {
        return new JAXBElement<QueryGLHistoryResponse>(_QueryGLHistoryResponse_QNAME, QueryGLHistoryResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CreateDepositAccountResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://api.PHilae/", name = "createDepositAccountResponse")
    public JAXBElement<CreateDepositAccountResponse> createCreateDepositAccountResponse(CreateDepositAccountResponse value) {
        return new JAXBElement<CreateDepositAccountResponse>(_CreateDepositAccountResponse_QNAME, CreateDepositAccountResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PostCashPaymentResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://api.PHilae/", name = "postCashPaymentResponse")
    public JAXBElement<PostCashPaymentResponse> createPostCashPaymentResponse(PostCashPaymentResponse value) {
        return new JAXBElement<PostCashPaymentResponse>(_PostCashPaymentResponse_QNAME, PostCashPaymentResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PostCashWithdrawalResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://api.PHilae/", name = "postCashWithdrawalResponse")
    public JAXBElement<PostCashWithdrawalResponse> createPostCashWithdrawalResponse(PostCashWithdrawalResponse value) {
        return new JAXBElement<PostCashWithdrawalResponse>(_PostCashWithdrawalResponse_QNAME, PostCashWithdrawalResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PostGLToDepositTransferResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://api.PHilae/", name = "postGLToDepositTransferResponse")
    public JAXBElement<PostGLToDepositTransferResponse> createPostGLToDepositTransferResponse(PostGLToDepositTransferResponse value) {
        return new JAXBElement<PostGLToDepositTransferResponse>(_PostGLToDepositTransferResponse_QNAME, PostGLToDepositTransferResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LoginUserResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://api.PHilae/", name = "loginUserResponse")
    public JAXBElement<LoginUserResponse> createLoginUserResponse(LoginUserResponse value) {
        return new JAXBElement<LoginUserResponse>(_LoginUserResponse_QNAME, LoginUserResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PostDepositToGLTransferResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://api.PHilae/", name = "postDepositToGLTransferResponse")
    public JAXBElement<PostDepositToGLTransferResponse> createPostDepositToGLTransferResponse(PostDepositToGLTransferResponse value) {
        return new JAXBElement<PostDepositToGLTransferResponse>(_PostDepositToGLTransferResponse_QNAME, PostDepositToGLTransferResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EnrollMobileChannelUser }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://api.PHilae/", name = "enrollMobileChannelUser")
    public JAXBElement<EnrollMobileChannelUser> createEnrollMobileChannelUser(EnrollMobileChannelUser value) {
        return new JAXBElement<EnrollMobileChannelUser>(_EnrollMobileChannelUser_QNAME, EnrollMobileChannelUser.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PostCashWithdrawal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://api.PHilae/", name = "postCashWithdrawal")
    public JAXBElement<PostCashWithdrawal> createPostCashWithdrawal(PostCashWithdrawal value) {
        return new JAXBElement<PostCashWithdrawal>(_PostCashWithdrawal_QNAME, PostCashWithdrawal.class, null, value);
    }

}
