
package philae.api;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "XAService", targetNamespace = "http://api.PHilae/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface XAService {


    /**
     * 
     * @param request
     * @return
     *     returns philae.api.CaResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createDepositAccount", targetNamespace = "http://api.PHilae/", className = "philae.api.CreateDepositAccount")
    @ResponseWrapper(localName = "createDepositAccountResponse", targetNamespace = "http://api.PHilae/", className = "philae.api.CreateDepositAccountResponse")
    @Action(input = "http://api.PHilae/XAService/createDepositAccountRequest", output = "http://api.PHilae/XAService/createDepositAccountResponse")
    public CaResponse createDepositAccount(
        @WebParam(name = "request", targetNamespace = "")
        CaRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns philae.api.XaResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "queryDepositBalance", targetNamespace = "http://api.PHilae/", className = "philae.api.QueryDepositBalance")
    @ResponseWrapper(localName = "queryDepositBalanceResponse", targetNamespace = "http://api.PHilae/", className = "philae.api.QueryDepositBalanceResponse")
    @Action(input = "http://api.PHilae/XAService/queryDepositBalanceRequest", output = "http://api.PHilae/XAService/queryDepositBalanceResponse")
    public XaResponse queryDepositBalance(
        @WebParam(name = "request", targetNamespace = "")
        BlRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns philae.api.XaResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "postDepositToGLTransfer", targetNamespace = "http://api.PHilae/", className = "philae.api.PostDepositToGLTransfer")
    @ResponseWrapper(localName = "postDepositToGLTransferResponse", targetNamespace = "http://api.PHilae/", className = "philae.api.PostDepositToGLTransferResponse")
    @Action(input = "http://api.PHilae/XAService/postDepositToGLTransferRequest", output = "http://api.PHilae/XAService/postDepositToGLTransferResponse")
    public XaResponse postDepositToGLTransfer(
        @WebParam(name = "request", targetNamespace = "")
        TxRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns philae.api.XaResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "postGLToGLTransfer", targetNamespace = "http://api.PHilae/", className = "philae.api.PostGLToGLTransfer")
    @ResponseWrapper(localName = "postGLToGLTransferResponse", targetNamespace = "http://api.PHilae/", className = "philae.api.PostGLToGLTransferResponse")
    @Action(input = "http://api.PHilae/XAService/postGLToGLTransferRequest", output = "http://api.PHilae/XAService/postGLToGLTransferResponse")
    public XaResponse postGLToGLTransfer(
        @WebParam(name = "request", targetNamespace = "")
        TxRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns philae.api.XaResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "postGLToDepositTransfer", targetNamespace = "http://api.PHilae/", className = "philae.api.PostGLToDepositTransfer")
    @ResponseWrapper(localName = "postGLToDepositTransferResponse", targetNamespace = "http://api.PHilae/", className = "philae.api.PostGLToDepositTransferResponse")
    @Action(input = "http://api.PHilae/XAService/postGLToDepositTransferRequest", output = "http://api.PHilae/XAService/postGLToDepositTransferResponse")
    public XaResponse postGLToDepositTransfer(
        @WebParam(name = "request", targetNamespace = "")
        TxRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns philae.api.XaResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "saveTerminal", targetNamespace = "http://api.PHilae/", className = "philae.api.SaveTerminal")
    @ResponseWrapper(localName = "saveTerminalResponse", targetNamespace = "http://api.PHilae/", className = "philae.api.SaveTerminalResponse")
    @Action(input = "http://api.PHilae/XAService/saveTerminalRequest", output = "http://api.PHilae/XAService/saveTerminalResponse")
    public XaResponse saveTerminal(
        @WebParam(name = "request", targetNamespace = "")
        TmRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns philae.api.XaResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteTerminal", targetNamespace = "http://api.PHilae/", className = "philae.api.DeleteTerminal")
    @ResponseWrapper(localName = "deleteTerminalResponse", targetNamespace = "http://api.PHilae/", className = "philae.api.DeleteTerminalResponse")
    @Action(input = "http://api.PHilae/XAService/deleteTerminalRequest", output = "http://api.PHilae/XAService/deleteTerminalResponse")
    public XaResponse deleteTerminal(
        @WebParam(name = "request", targetNamespace = "")
        TmRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns philae.api.TmResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "queryTerminal", targetNamespace = "http://api.PHilae/", className = "philae.api.QueryTerminal")
    @ResponseWrapper(localName = "queryTerminalResponse", targetNamespace = "http://api.PHilae/", className = "philae.api.QueryTerminalResponse")
    @Action(input = "http://api.PHilae/XAService/queryTerminalRequest", output = "http://api.PHilae/XAService/queryTerminalResponse")
    public TmResponse queryTerminal(
        @WebParam(name = "request", targetNamespace = "")
        StRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns philae.api.AqResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "queryDepositAccount", targetNamespace = "http://api.PHilae/", className = "philae.api.QueryDepositAccount")
    @ResponseWrapper(localName = "queryDepositAccountResponse", targetNamespace = "http://api.PHilae/", className = "philae.api.QueryDepositAccountResponse")
    @Action(input = "http://api.PHilae/XAService/queryDepositAccountRequest", output = "http://api.PHilae/XAService/queryDepositAccountResponse")
    public AqResponse queryDepositAccount(
        @WebParam(name = "request", targetNamespace = "")
        AqRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns philae.api.CcResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createCustomer", targetNamespace = "http://api.PHilae/", className = "philae.api.CreateCustomer")
    @ResponseWrapper(localName = "createCustomerResponse", targetNamespace = "http://api.PHilae/", className = "philae.api.CreateCustomerResponse")
    @Action(input = "http://api.PHilae/XAService/createCustomerRequest", output = "http://api.PHilae/XAService/createCustomerResponse")
    public CcResponse createCustomer(
        @WebParam(name = "request", targetNamespace = "")
        CcRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns philae.api.CcResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "modifyCustomer", targetNamespace = "http://api.PHilae/", className = "philae.api.ModifyCustomer")
    @ResponseWrapper(localName = "modifyCustomerResponse", targetNamespace = "http://api.PHilae/", className = "philae.api.ModifyCustomerResponse")
    @Action(input = "http://api.PHilae/XAService/modifyCustomerRequest", output = "http://api.PHilae/XAService/modifyCustomerResponse")
    public CcResponse modifyCustomer(
        @WebParam(name = "request", targetNamespace = "")
        CcRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns philae.api.UlResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "loginUser", targetNamespace = "http://api.PHilae/", className = "philae.api.LoginUser")
    @ResponseWrapper(localName = "loginUserResponse", targetNamespace = "http://api.PHilae/", className = "philae.api.LoginUserResponse")
    @Action(input = "http://api.PHilae/XAService/loginUserRequest", output = "http://api.PHilae/XAService/loginUserResponse")
    public UlResponse loginUser(
        @WebParam(name = "request", targetNamespace = "")
        UlRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns philae.api.LhResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "queryGLHistory", targetNamespace = "http://api.PHilae/", className = "philae.api.QueryGLHistory")
    @ResponseWrapper(localName = "queryGLHistoryResponse", targetNamespace = "http://api.PHilae/", className = "philae.api.QueryGLHistoryResponse")
    @Action(input = "http://api.PHilae/XAService/queryGLHistoryRequest", output = "http://api.PHilae/XAService/queryGLHistoryResponse")
    public LhResponse queryGLHistory(
        @WebParam(name = "request", targetNamespace = "")
        LhRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns philae.api.XaResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "postCashPayment", targetNamespace = "http://api.PHilae/", className = "philae.api.PostCashPayment")
    @ResponseWrapper(localName = "postCashPaymentResponse", targetNamespace = "http://api.PHilae/", className = "philae.api.PostCashPaymentResponse")
    @Action(input = "http://api.PHilae/XAService/postCashPaymentRequest", output = "http://api.PHilae/XAService/postCashPaymentResponse")
    public XaResponse postCashPayment(
        @WebParam(name = "request", targetNamespace = "")
        CpRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns philae.api.LtResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listTerminals", targetNamespace = "http://api.PHilae/", className = "philae.api.ListTerminals")
    @ResponseWrapper(localName = "listTerminalsResponse", targetNamespace = "http://api.PHilae/", className = "philae.api.ListTerminalsResponse")
    @Action(input = "http://api.PHilae/XAService/listTerminalsRequest", output = "http://api.PHilae/XAService/listTerminalsResponse")
    public LtResponse listTerminals(
        @WebParam(name = "request", targetNamespace = "")
        TqRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns philae.api.XaResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "enrollMobileChannelUser", targetNamespace = "http://api.PHilae/", className = "philae.api.EnrollMobileChannelUser")
    @ResponseWrapper(localName = "enrollMobileChannelUserResponse", targetNamespace = "http://api.PHilae/", className = "philae.api.EnrollMobileChannelUserResponse")
    @Action(input = "http://api.PHilae/XAService/enrollMobileChannelUserRequest", output = "http://api.PHilae/XAService/enrollMobileChannelUserResponse")
    public XaResponse enrollMobileChannelUser(
        @WebParam(name = "request", targetNamespace = "")
        CuRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns philae.api.DhResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "queryDepositHistory", targetNamespace = "http://api.PHilae/", className = "philae.api.QueryDepositHistory")
    @ResponseWrapper(localName = "queryDepositHistoryResponse", targetNamespace = "http://api.PHilae/", className = "philae.api.QueryDepositHistoryResponse")
    @Action(input = "http://api.PHilae/XAService/queryDepositHistoryRequest", output = "http://api.PHilae/XAService/queryDepositHistoryResponse")
    public DhResponse queryDepositHistory(
        @WebParam(name = "request", targetNamespace = "")
        DhRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns philae.api.XaResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "activateDepositAccount", targetNamespace = "http://api.PHilae/", className = "philae.api.ActivateDepositAccount")
    @ResponseWrapper(localName = "activateDepositAccountResponse", targetNamespace = "http://api.PHilae/", className = "philae.api.ActivateDepositAccountResponse")
    @Action(input = "http://api.PHilae/XAService/activateDepositAccountRequest", output = "http://api.PHilae/XAService/activateDepositAccountResponse")
    public XaResponse activateDepositAccount(
        @WebParam(name = "request", targetNamespace = "")
        AaRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns philae.api.AqResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "queryLedgerAccount", targetNamespace = "http://api.PHilae/", className = "philae.api.QueryLedgerAccount")
    @ResponseWrapper(localName = "queryLedgerAccountResponse", targetNamespace = "http://api.PHilae/", className = "philae.api.QueryLedgerAccountResponse")
    @Action(input = "http://api.PHilae/XAService/queryLedgerAccountRequest", output = "http://api.PHilae/XAService/queryLedgerAccountResponse")
    public AqResponse queryLedgerAccount(
        @WebParam(name = "request", targetNamespace = "")
        AqRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns philae.api.XaResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "postCashWithdrawal", targetNamespace = "http://api.PHilae/", className = "philae.api.PostCashWithdrawal")
    @ResponseWrapper(localName = "postCashWithdrawalResponse", targetNamespace = "http://api.PHilae/", className = "philae.api.PostCashWithdrawalResponse")
    @Action(input = "http://api.PHilae/XAService/postCashWithdrawalRequest", output = "http://api.PHilae/XAService/postCashWithdrawalResponse")
    public XaResponse postCashWithdrawal(
        @WebParam(name = "request", targetNamespace = "")
        CpRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns philae.api.XaResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "postTransferPayment", targetNamespace = "http://api.PHilae/", className = "philae.api.PostTransferPayment")
    @ResponseWrapper(localName = "postTransferPaymentResponse", targetNamespace = "http://api.PHilae/", className = "philae.api.PostTransferPaymentResponse")
    @Action(input = "http://api.PHilae/XAService/postTransferPaymentRequest", output = "http://api.PHilae/XAService/postTransferPaymentResponse")
    public XaResponse postTransferPayment(
        @WebParam(name = "request", targetNamespace = "")
        TpRequest request);

}
