
package philae.api;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "XAService", targetNamespace = "http://api.PHilae/", wsdlLocation = "file:/D:/amecore/cilantro/src/main/resources/philae.wsdl")
public class XAService_Service
    extends Service
{

    private final static URL XASERVICE_WSDL_LOCATION;
    private final static WebServiceException XASERVICE_EXCEPTION;
    private final static QName XASERVICE_QNAME = new QName("http://api.PHilae/", "XAService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/D:/amecore/cilantro/src/main/resources/philae.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        XASERVICE_WSDL_LOCATION = url;
        XASERVICE_EXCEPTION = e;
    }

    public XAService_Service() {
        super(__getWsdlLocation(), XASERVICE_QNAME);
    }

    public XAService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), XASERVICE_QNAME, features);
    }

    public XAService_Service(URL wsdlLocation) {
        super(wsdlLocation, XASERVICE_QNAME);
    }

    public XAService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, XASERVICE_QNAME, features);
    }

    public XAService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public XAService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns XAService
     */
    @WebEndpoint(name = "XAServicePort")
    public XAService getXAServicePort() {
        return super.getPort(new QName("http://api.PHilae/", "XAServicePort"), XAService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns XAService
     */
    @WebEndpoint(name = "XAServicePort")
    public XAService getXAServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://api.PHilae/", "XAServicePort"), XAService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (XASERVICE_EXCEPTION!= null) {
            throw XASERVICE_EXCEPTION;
        }
        return XASERVICE_WSDL_LOCATION;
    }

}
